spring:
  datasource:
    url: jdbc:h2:mem:testdb;DB_CLOSE_ON_EXIT=FALSE
    driver-class-name: org.h2.Driver
    username: sa
    password:
  h2:
    console:
      path: /h2-console
      enabled: true
  jpa:
    show-sql: true
    open-in-view: false
    hibernate:
      ddl-auto: create-drop
      use-new-id-generator-mappings: false
    defer-datasource-initialization: true
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true
  jackson:
    property-naming-strategy: SNAKE_CASE

logging.level.org.hibernate.type.descriptor.sql: trace

server:
  port: 9090